# Shell snippet: run AFTER git-hooks.nix's installation script, so that
# installing pre-commit/prek hooks does not switch Reprobuild's hooks off.
#
# WHY THIS EXISTS.
#
# In a Reprobuild workspace each `.git/hooks/<hook>` is a Reprobuild DISPATCHER
# ("# reprobuild hook dispatcher protocol=2"). It runs the repo's own hooks,
# preserved as `<hook>.repro-local`, and then Reprobuild's managed hook,
# `<hook>.repro-managed` — for `pre-push` that is the publication gate
# (`repro check --mode=pre-push`).
#
# Upstream's installation script runs `prek uninstall -t <every hook type>` and
# then `prek install -t <each configured stage>`. `prek install` (and
# `pre-commit install`) finds the dispatcher in its way, MOVES it to
# `<hook>.legacy` ("migration mode") and writes its own shim in its place. The
# managed hook then runs only as a side effect of prek's migration chain, and
# `repro hooks ensure` has to repair the layout afterwards. Agents hit this
# repeatedly and restored the dispatchers by hand.
#
# THE HANDOFF. After the installer, for every `<hook>.legacy` that is a
# dispatcher:
#
#   * the slot holds a freshly generated pre-commit/prek shim -> chain that
#     shim as `<hook>.repro-local` (replacing a previously chained shim, which
#     is the same tool's output) and put the dispatcher back in the slot;
#   * the slot is empty -> put the dispatcher back;
#   * the slot already holds a dispatcher -> the `.legacy` copy is a stale
#     duplicate; drop it (a chained shim would otherwise run it and re-enter
#     the dispatcher);
#   * anything else (a hand-written hook in the slot, or a hand-written
#     `.repro-local` the shim would overwrite) -> touch nothing and say so;
#     `repro hooks ensure --vcs` reconciles or refuses with both paths named.
#
# The result is exactly the layout `repro hooks ensure` produces, so the next
# `ensure` has nothing to do. A repository with no Reprobuild dispatcher has no
# dispatcher at `<hook>.legacy`, and this does nothing at all to it: prek's
# hooks install and run exactly as upstream leaves them.
#
# core.hooksPath. Upstream finishes with
#   git config --local core.hooksPath "<common dir relative to the worktree>/hooks"
# which in a main checkout is `.git/hooks`: RELATIVE. Git resolves a relative
# hooksPath against the worktree it is running in, and in a linked worktree
# `.git` is a file, so `.git/hooks` does not exist there and Git runs NO hooks
# in any linked worktree of the repository — neither prek's nor Reprobuild's.
# The value names the common hooks directory, so it is rewritten as that
# absolute path, which every worktree resolves identically.
#
# Nothing here fails the shell: a devShell that refuses to open because a hook
# file could not be moved is worse than the drift, which `repro health`
# reports with its own remedy.
{ git }:
''
  _mcl_hooks_reprobuild_handoff() {
    local common hooks hp top resolved legacy slot local_hook name
    common="$(${git} rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" || return 0
    [ -n "$common" ] || return 0
    hooks="$common/hooks"
    [ -d "$hooks" ] || return 0

    # A relative core.hooksPath that names the common hooks directory is
    # made absolute (see the header).
    hp="$(${git} config --local --get core.hooksPath 2>/dev/null || true)"
    if [ -n "$hp" ] && [ "''${hp#/}" = "$hp" ]; then
      top="$(${git} rev-parse --show-toplevel 2>/dev/null || true)"
      resolved="$(cd "$top" 2>/dev/null && cd "$hp" 2>/dev/null && pwd -P || true)"
      if [ "$hp" = ".git/hooks" ] || [ "$resolved" = "$(cd "$hooks" && pwd -P)" ]; then
        ${git} config --local core.hooksPath "$hooks" || true
      fi
    fi

    for legacy in "$hooks"/*.legacy; do
      [ -f "$legacy" ] || continue
      grep -q 'reprobuild hook dispatcher' "$legacy" 2>/dev/null || continue
      slot="''${legacy%.legacy}"
      name="$(basename "$slot")"
      local_hook="$slot.repro-local"
      if [ -f "$slot" ] && grep -q 'reprobuild hook dispatcher' "$slot" 2>/dev/null; then
        rm -f "$legacy"
        continue
      fi
      if [ -f "$slot" ]; then
        if ! grep -Eq '^# File generated by (pre-commit|prek):' "$slot" 2>/dev/null; then
          echo 1>&2 "git-hooks: $name is not a pre-commit/prek shim; leaving the Reprobuild dispatcher at $name.legacy."
          echo 1>&2 "           Run 'repro hooks ensure --vcs' to reconcile."
          continue
        fi
        if [ -f "$local_hook" ] && ! grep -Eq '^# File generated by (pre-commit|prek):' "$local_hook" 2>/dev/null; then
          echo 1>&2 "git-hooks: $name.repro-local holds your own hook; not replacing it with the generated shim."
          echo 1>&2 "           Run 'repro hooks ensure --vcs' to reconcile."
          continue
        fi
        mv -f "$slot" "$local_hook" || continue
        chmod +x "$local_hook" 2>/dev/null || true
      fi
      mv -f "$legacy" "$slot" || continue
      echo 1>&2 "git-hooks: kept the Reprobuild dispatcher at .git/hooks/$name (hook manager chained as $name.repro-local)"
    done
    return 0
  }
''
