# Upstream git-hooks.nix's OWN installation script, run with the module's
# `gitPackage` (lib/git-hooks-same-repo-git.nix), installs nothing into a
# repository other than the flake's, and still installs in the flake's own.
#
# This is the path `inputsFrom = [ config.pre-commit.devShell ]`,
# `pre-commit.installationScript` and `pre-commit.shellHook` take: upstream's
# script, unwrapped. The script under test is the real one, generated by the
# pinned git-hooks.nix from a real `run` evaluation, executed in real git
# repositories:
#
#   1. a repository whose flake.nix is a different file, a repository with no
#      flake.nix, and a subdirectory of the first: no `.pre-commit-config.yaml`,
#      no hook, no `core.hooksPath`;
#   2. the flake's own repository (a flake.nix with the expected content),
#      entered from a subdirectory: the installer runs (`core.hooksPath` set,
#      a pre-commit hook installed).
#
# Run with `gitPackage = pkgs.gitMinimal` (upstream's default) case 1 fails:
# that is the defect.
{ inputs, ... }:
{
  perSystem =
    {
      pkgs,
      lib,
      system,
      ...
    }:
    let
      ownFlakeNix = ''
        { description = "fixture: the flake this devShell belongs to"; outputs = _: { }; }
      '';
      guardedGit = import ../lib/git-hooks-same-repo-git.nix {
        inherit pkgs;
        expectedFlakeNixHash = builtins.hashString "sha256" ownFlakeNix;
      };
      project = inputs.git-hooks-nix.lib.${system}.run {
        src = pkgs.emptyDirectory;
        package = pkgs.prek;
        gitPackage = guardedGit;
        hooks.trim-trailing-whitespace.enable = true;
      };
    in
    {
      checks.git-hooks-same-repo-git =
        pkgs.runCommand "git-hooks-same-repo-git"
          {
            nativeBuildInputs = [
              pkgs.git
              pkgs.coreutils
            ];
            installationScript = project.config.installationScript;
            inherit ownFlakeNix;
            passAsFile = [
              "installationScript"
              "ownFlakeNix"
            ];
          }
          ''
            set -euo pipefail
            export HOME="$TMPDIR/home" PREK_HOME="$TMPDIR/prek-home"
            mkdir -p "$HOME"
            git config --global user.email check@example.invalid
            git config --global user.name check
            git config --global init.defaultBranch main
            fail() { echo "FAIL: $*" >&2; exit 1; }

            new_repo() {
              mkdir -p "$1"; git -C "$1" init -q
              git -C "$1" commit -q --allow-empty -m init
            }
            enter() { (cd "$1" && bash "$installationScriptPath") || true; }
            untouched() {
              [ ! -e "$1/.pre-commit-config.yaml" ] || fail "$2: .pre-commit-config.yaml was written"
              [ -z "$(git -C "$1" config --local --get core.hooksPath || true)" ] || fail "$2: core.hooksPath was set"
              [ ! -e "$1/.git/hooks/pre-commit" ] || fail "$2: a pre-commit hook was installed"
            }

            echo "== 1. other repositories stay untouched"
            new_repo "$TMPDIR/other"
            echo '{ outputs = _: { }; }' > "$TMPDIR/other/flake.nix"
            mkdir -p "$TMPDIR/other/sub"
            enter "$TMPDIR/other"
            untouched "$TMPDIR/other" "different flake.nix"
            enter "$TMPDIR/other/sub"
            untouched "$TMPDIR/other" "different flake.nix, from a subdirectory"
            new_repo "$TMPDIR/bare"
            enter "$TMPDIR/bare"
            untouched "$TMPDIR/bare" "no flake.nix"

            echo "== 2. the flake's own repository still gets its hooks"
            new_repo "$TMPDIR/own"
            cp "$ownFlakeNixPath" "$TMPDIR/own/flake.nix"
            mkdir -p "$TMPDIR/own/sub"
            enter "$TMPDIR/own/sub"
            [ -n "$(git -C "$TMPDIR/own" config --local --get core.hooksPath || true)" ] \
              || fail "own repository: the installer did not run (core.hooksPath unset)"
            [ -e "$TMPDIR/own/.git/hooks/pre-commit" ] \
              || fail "own repository: no pre-commit hook was installed"

            touch "$out"
          '';
    };
}
